name: Create release & Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm just godot git python unzip clang npm github-cli zip

      # INFO: Cache information:
      # .deps includes the rust nightly installation at the time of caching, therefore we can also cache the rust builds
      # from ./rust/target reducing time taken for subsequent actions.
      - name: Restore dependencies and previous build from cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ./.deps
            ./rust/target
            ~/.local/share/godot/export_templates
          key: setup-cache-${{ runner.os }}-${{ hashFiles('justfile') }}
          restore-keys: |
            setup-cache-${{ runner.os }}-${{ hashFiles('justfile') }}


      - name: Run setup (if not cached)
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          [ -d "./.deps" ] && echo "cache was found" || just _setup-ci-cd 

      - name: Export Web
        run: |
          just release-web
          cp -r web_assets/* target/web

      - name: Save cache (if missing)
        if: steps.cache-restore.outputs.cache-hit != 'true'
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            ./.deps
            ./rust/target
            ~/.local/share/godot/export_templates
          key: setup-cache-${{ runner.os }}-${{ hashFiles('justfile') }}


      - name: Install Netlify cli
        continue-on-error: true
        run: |
          npm install -g netlify-cli
      - name: Deploy to Netlify
        continue-on-error: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          netlify deploy --dir=target/web --prod --site=${{ secrets.NETLIFY_SITE_ID }}

      - name: Zip Web Export
        run: |
          cd target/web
          zip -r web-export.zip ./*
          mv web-export.zip ../..
