name: Create release & Deploy

on:
  push:
    tags:
      - '*'

jobs:
  wait-for-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Cache Setup
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: "cache.yml" # Name of the Cache Setup workflow
          ref: main  # Reference the `main` branch to ensure cache setup is from `main`

  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm just godot git python unzip clang npm github-cli zip

      - name: Wait for cache to be built from main
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.repository.default_branch }}
          check-name: 'Setup cache'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      # INFO: Cache information:
      # .deps includes the rust nightly installation at the time of caching, therefore we can also cache the rust builds
      # from ./rust/target reducing time taken for subsequent actions.
      - name: Restore dependencies and previous build from cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ./.deps
            ./rust/target
            ~/.local/share/godot/export_templates
          key: cache-${{ runner.os }}-${{ hashFiles('justfile') }}
          restore-keys: |
            cache-${{ runner.os }}-${{ hashFiles('justfile') }}

      - name: Check if cache was restored from
        id: cache-check
        run: |
          if [ -d "./.deps" ]; then
            echo "cache-found=true" >> $GITHUB_ENV
          else
            echo "cache-found=false" >> $GITHUB_ENV
          fi


      - name: Run setup (if not cached)
        if: env.cache-found == 'false'
        run: |
          just _setup-ci-cd 

      - name: Export Web
        run: |
          just release-web
          cp -r web_assets/* target/web


      - name: Install Netlify cli
        continue-on-error: true
        run: |
          npm install -g netlify-cli
      - name: Deploy to Netlify
        continue-on-error: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          netlify deploy --dir=target/web --prod --site=${{ secrets.NETLIFY_SITE_ID }}

      - name: Zip Web Export
        run: |
          cd target/web
          zip -r web-export.zip ./*
          mv web-export.zip ../..
