name: Cache Setup
on:
  push:
    branches:
      - main  # Run only on main branch
    paths:
      - ./justfile
jobs:
  setup-cache:
    name: Setup cache
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm just godot git python unzip clang npm github-cli zip

      - name: Run Setup
        run: just _setup-ci-cd  # Ensure dependencies are built

      - name: Save Cache
        uses: actions/cache/save@v4
        with:
          path: |
            ./.deps
            ./rust/target
            ~/.local/share/godot/export_templates
          key: cache-${{ runner.os }}-${{ hashFiles('justfile') }}

